name:   Hello World!

on:
    push:
       branches:
        -   main

jobs:
    hello_world_job:
        runs-on: ubuntu-20.04
        steps:
          - name: Say Hello
            run: |
                echo "Hello World!"
                
    now_it_is_job:
        runs-on: ubuntu-20.04
        steps:
            - name: Now It is
              run: |
                date


    directory_content_job:
         runs-on: ubuntu-20.04
         steps:
             - name: Directory Content
               run: |
                ls -l
 
                
    
